range_spectrum:	range_spectrum.cpp
	`root-config --cxx --cflags` -o range_spectrum range_spectrum.cpp `root-config --glibs`

energy_dependence:	energy_dependence.cpp
	`root-config --cxx --cflags` -o energy_dependence energy_dependence.cpp `root-config --glibs`

energy_degradation:	energy_degradation.cpp
	`root-config --cxx --cflags` -o energy_degradation energy_degradation.cpp `root-config --glibs`
